export const MAC_APPS = {
  Calculator: "webp",
  ChatGPT: "webp",
  Chrome: "webp",
  Discord: "webp",
  Edge: "webp",
  "Epic Games Launcher": "webp",
  Facetime: "webp",
  FileZilla: "webp",
  Finder: "webp",
  Firefox: "webp",
  "Google Drive": "webp",
  "HBO Max": "webp",
  Mail: "webp",
  Messages: "webp",
  "Microsoft Excel": "webp",
  "Microsoft OneNote": "webp",
  "Microsoft Outlook": "webp",
  "Microsoft PowerPoint": "webp",
  "Microsoft Word": "webp",
  Minecraft: "webp",
  Music: "webp",
  Notion: "webp",
  Obsidian: "webp",
  Photoshop: "webp",
  PyCharm: "webp",
  Safari: "webp",
  "System Preferences": "webp",
  TikTok: "webp",
  Todoist: "webp",
  Weather: "webp",
  Xcode: "webp",
  "Zen Browser": "webp",
};

export const WINDOWS_APPS = {
  "Control Panel": "webp",
  "Edge Beta": "webp",
  "Edge Canary": "webp",
  "Edge Developer": "webp",
  Edge: "webp",
  OneDrive: "webp",
  Planner: "webp",
  PowerToys: "webp",
  "Remote Desktop": "webp",
  Search: "webp",
  Settings: "webp",
  Start: "webp",
  Stream: "webp",
  Tasks: "webp",
  Teams: "webp",
  TV: "webp",
  "Visual Blend": "webp",
  "Visual Studio Code": "webp",
  "Visual Studio Preview": "webp",
  "Visual Studio": "webp",
  Widgets: "webp",
};

export const OS_SEPARATOR = "***";
export const ITEM_SEPARATOR = "//";
