export const MAC_APPS = {
  Calculator: "webp",
  ChatGPT: "webp",
  Chrome: "webp",
  Discord: "webp",
  Edge: "webp",
  "Epic Games Launcher": "webp",
  Facetime: "webp",
  FileZilla: "webp",
  Finder: "webp",
  Firefox: "webp",
  "Google Drive": "webp",
  "HBO Max": "webp",
  Mail: "webp",
  Messages: "webp",
  "Microsoft Excel": "webp",
  "Microsoft OneNote": "webp",
  "Microsoft Outlook": "webp",
  "Microsoft PowerPoint": "webp",
  "Microsoft Word": "webp",
  Minecraft: "webp",
  Music: "webp",
  Notion: "webp",
  Obsidian: "webp",
  Photoshop: "webp",
  PyCharm: "webp",
  Safari: "webp",
  "System Preferences": "webp",
  TikTok: "webp",
  Todoist: "webp",
  Weather: "webp",
  Xcode: "webp",
  "Zen Browser": "webp",
};

export const WINDOWS_APPS = {
  Access: "webp",
  Azure: "webp",
  Calculator: "webp",
  Calendar: "webp",
  Camera: "webp",
  Clock: "webp",
  "Control Panel": "webp",
  "Edge Beta": "webp",
  "Edge Canary": "webp",
  "Edge Developer": "webp",
  Edge: "webp",
  Excel: "webp",
  Mail: "webp",
  News: "webp",
  Notepad: "webp",
  Office: "webp",
  OneDrive: "webp",
  OneNote: "webp",
  Outlook: "webp",
  Paint: "webp",
  People: "webp",
  Photos: "webp",
  Planner: "webp",
  PowerPoint: "webp",
  PowerToys: "webp",
  "Remote Desktop": "webp",
  Search: "webp",
  Settings: "webp",
  SharePoint: "webp",
  Skype: "webp",
  "Snip and Sketch": "webp",
  "Snipping Tool": "webp",
  Solitaire: "webp",
  Start: "webp",
  "Sticky Notes": "webp",
  Store: "webp",
  Stream: "webp",
  "Task Manager": "webp",
  Tasks: "webp",
  Teams: "webp",
  "Terminal Developer": "webp",
  "Terminal Preview": "webp",
  Terminal: "webp",
  Tips: "webp",
  TV: "webp",
  "Video Editor": "webp",
  Visio: "webp",
  "Visual Blend": "webp",
  "Visual Studio Code - Insiders": "webp",
  "Visual Studio Code": "webp",
  "Visual Studio Preview": "webp",
  "Visual Studio": "webp",
  Visualize: "webp",
  Voice: "webp",
  Weather: "webp",
  Whiteboard: "webp",
  Widgets: "webp",
  Word: "webp",
  Workbooks: "webp",
  Yammer: "webp",
  "Your Phone": "webp",
};

export const OS_SEPARATOR = "***";
export const ITEM_SEPARATOR = "//";
