export const MAC_APPS = {
  Calculator: "webp",
  Chrome: "webp",
  Facetime: "webp",
  Finder: "webp",
  Firefox: "webp",
  "Google Drive": "webp",
  Mail: "webp",
  Messages: "webp",
  "Microsoft Excel": "webp",
  "Microsoft OneNote": "webp",
  "Microsoft Outlook": "webp",
  "Microsoft PowerPoint": "webp",
  "Microsoft Word": "webp",
  Music: "webp",
  Notion: "webp",
  Safari: "webp",
  "System Preferences": "webp",
  Todoist: "webp",
  Weather: "webp",
  Xcode: "webp",
  "Zen Browser": "webp",
};
export const OS_SEPARATOR = "***";
export const ITEM_SEPARATOR = "//";
